---
# List OP players and check if player is OP using command
# Copyright (C) 2021 KygekDev
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# he Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

name: IsOP
version: 1.0.0
description: List OP players and check if player is OP using command
author: KygekDev
website: https://github.com/KygekDev/IsOP
api: 4.0.0
main: KygekDev\IsOP\IsOP

commands: 
  isop:
    description: List OP players or check if player is OP
    usage: /isop [player]
    permission: isop.command

permissions: 
  isop.command:
    description: Permission to use IsOP plugin command
    default: op
...